spring:
  datasource:
    url: jdbc:h2:file:./data/auth_db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: NEVER
    schema: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations:
    - /mappers/*.xml